max_width = 80
format_code_in_doc_comments = true
format_strings = true
fn_single_line = true
group_imports = "StdExternalCrate"
match_block_trailing_comma = true
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_small_heuristics = "Max"

# couldn't find:
# - setting for there to put trailing method calls
# - setting for allowing single-line control flow statements
